"""Render the field reference from the resolved dataclass defaults."""
from dataclasses import asdict, fields, is_dataclass
import json
from pathlib import Path

from resultsgen.config import AppConfig, Config, load_config


def render():
    lines = ["# Configuration reference", "", "Generated by `scripts/config_reference.py` from the dataclass schema.", "",
             "Omitted fields take these defaults. Unknown fields are rejected. Dates and times are local to `timezone`.", "",
             "| Field | Default |", "| --- | --- |"]

    def walk(value, prefix=""):
        for field in fields(value):
            item = getattr(value, field.name)
            name = prefix + field.name
            if is_dataclass(item):
                walk(item, name + ".")
            elif field.name == "apps":
                walk(AppConfig(), "apps[].")
            elif isinstance(item, dict) and item and all(is_dataclass(v) for v in item.values()):
                for key, entry in item.items():
                    walk(entry, name + "." + key + ".")
            else:
                lines.append(f"| `{name}` | `{json.dumps(item, ensure_ascii=False)}` |")

    walk(load_config({}))
    lines.extend(["", "App duration ranges are resolved from test count: ≥10,000 → [180,360], ≥2,000 → [40,120], otherwise [8,45] minutes.",
                  "The default preset provides ten named apps; the generic `apps[]` row above describes defaults for a new app.",
                  "Event shapes and target selectors are described in [README.md](README.md).", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    Path(__file__).resolve().parents[1].joinpath("CONFIGURATION.md").write_text(render(), encoding="utf-8")
